common:
  copyrightText: "<#FFFF99>Protected from duplication"
  copyrightAuthorName: "<#FFFF99>© <#9AFF0F><arg1>"
  copyrightLegacyStrings:
    - "Copyrighted by"
banners:
  copyrightPrice: 20
pixelarts:
  copyrightPrice: 100
  previewInventories:
    - "Auction"
    - "Market"
    - "Shop"