commands:
  aliases:
    - pixelart
    - art
    - pxt
banners:
  copyrightPrice: 20
pixelarts:
  previewDuration: 100
  showArtCooldown: 300
  copyrightPrice: 100
  previewEverywhere: false
  previewInventories:
    - "Auction"
    - "Market"
    - "Shop"
  respectRegionProtection: true
  worldMapArt: world_map_art
lang: en
bStats: true