common:
  copyrightText: "<reset><#FFFF99>Защищено от копирования"
  copyrightAuthorName: "<reset><#FFFF99>© <#9AFF0F><arg1>"
  copyrightLegacyStrings:
    - "Copyrighted by"
banners:
  copyrightPrice: 20
:
  copyrightPrice: 100