name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
          cache: maven
      - name: Read artifact name, version, mc versions
        shell: bash
        run: |
          echo "artifact_id=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.artifactId -q -DforceStdout=true)" >> $GITHUB_ENV
          echo "artifact_version=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=project.version -q -DforceStdout=true)" >> $GITHUB_ENV
          echo "minecraft_versions=$(mvn org.apache.maven.plugins:maven-help-plugin:3.2.0:evaluate -Dexpression=minecraftVersions -q -DforceStdout=true)" >> $GITHUB_ENV
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Copy jar files to staging
        shell: bash
        run: |
          mkdir staging && cp target/${{ env.artifact_id }}-${{ env.artifact_version }}.jar staging
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
      - name: Prerelease
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, env.artifact_version) && endsWith(github.ref, '-SNAPSHOT')
        with:
          files: staging/*
          prerelease: true
          body: 'Supported Minecraft versions: ${{ env.minecraft_versions }}'
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v') && endsWith(github.ref, env.artifact_version) && !endsWith(github.ref, '-SNAPSHOT')
        with:
          files: staging/*
          prerelease: false
          body: 'Supported Minecraft versions: ${{ env.minecraft_versions }}'