name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      mc_version: '1.18.2'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Chache server jar
        id: cache-server-jar
        uses: actions/cache@v3
        with:
          path: ${{ mc_version }}.jar
          key: ${{ mc_version }}-server-jar
      - name: Download Minecraft server
        if: steps.cache-server-jar.outputs.cache-hit != 'true'
        run: wget https://api.purpurmc.org/v2/purpur/${{ mc_version }}/latest/download -O server.jar
      - name: Install jar to server
        run: |
          java -jar server.jar nogui
          mvn install:install-file -f pom_codeql.xml -Dfile="versions/${{mc_version}}/purpur-${{ mc_version }}.jar" -DgroupId=minecraft -DartifactId=minecraft -Dversion="${{ mc_version }}" -Dpackaging=jar
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package