name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      mc_version: '1.18.2'
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Cache server jar
        id: cache-server-jar
        uses: actions/cache@v3
        with:
          path: ${{ env.mc_version }}.jar
          key: ${{ env.mc_version }}-server-jar
      - name: Download Minecraft server
        if: steps.cache-server-jar.outputs.cache-hit != 'true'
        run: wget https://api.purpurmc.org/v2/purpur/${{ env.mc_version }}/latest/download -O ${{ env.mc_version }}.jar
      - name: Install jar to server
        run: |
          java -jar ${{ env.mc_version }}.jar nogui
          mvn install:install-file -Dfile="versions/${{ env.mc_version }}/purpur-${{ env.mc_version }}.jar" -DgroupId=minecraft -DartifactId=minecraft -Dversion="${{ env.mc_version }}" -Dpackaging=jar
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Set Release version env variable
        run: echo "release_version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV